Remove react-abc library
rage/musiikin-teoria-material pull request #153
Opened 2019-06-10 09:47 UTC by Vanamo

2019-06-10 09:48 UTC, AuroraLS3 requested changes

2019-06-10 09:48 UTC, Rsl1122 commented on src/components/music/MusicSheet.js
> -        {!renderSound && <div className="emptyPlayButton" />}
This needs to be added back

2019-06-10 09:52 UTC, Vanamo commented on src/components/music/MusicSheet.js
> -        {!renderSound && <div className="emptyPlayButton" />}
ok

2019-06-12 07:44 UTC, nigoshh commented on package.json
> -    "react-abc": "github:nigoshh/react-abc-mooc#build",
success!

2019-06-12 07:51 UTC, AuroraLS3 approved these changes

2019-06-12 07:52 UTC, nigoshh approved these changes
Great!

2019-06-12 07:54 UTC, merged